# Generated by Django 2.2.4 on 2019-08-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190827_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='author',
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='department',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='department',
            name='text',
        ),
        migrations.AddField(
            model_name='department',
            name='address',
            field=models.CharField(default=0, max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
